name: together_ai_sdk
description: A comprehensive SDK for interacting with the Together AI API. Supports chat, text, and image generation with various models including Llama 3.
version: 2.0.2
repository: https://github.com/ilovekimchi6/together-ai-dart


environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  dio: ^5.4.2+1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mocktail: ^1.0.3
