name: together_ai_sdk
description: Together AI SDK for Dart and Flutter.
version: 1.0.0
repository: https://github.com/ilovekimchi6/together-ai-dart

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  dio: ^5.4.2+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mocktail: ^1.0.3
